Create database Casestudy
Use Casestudy

Select* from Location

Select * from Fact

Select* from Product


--1. Display the number of states present in theLocationTable.
   

   Select Count(Distinct State) AS NO_OF_STATES from Location 

--2. Howmany products are of regular type?

Select Count(*) AS Count_Regular from Product Where Type='Regular'

--3. Howmuch spending has been done on marketing of product ID1?

Select SUM(Marketing) from Fact where ProductId=1

--4. What is the minimum sales of a product?

Select Min(Sales) AS Minimum_Sale from Fact

--5. Display the max Cost of Good Sold (COGS).

Select MAX(COGs) AS Max_COGs from Fact

--6. Display the details of the product where product type iscoffee.
Select * from Product where Product_Type='Coffee'

--7. Display the details where total expenses are greater than40.

Select * from Fact where Total_Expenses > 40;

--8. What is the average sales in area code 719?

Select Avg(Sales) AS Avg_Sales from Fact where Area_code= 719;

--9. Find out the total profit generated by Colorado state

Select SUM(F.Profit) AS Totalprofit from Fact AS F Join Location AS L ON F.Area_Code= L.Area_Code Where State = 'Colorado';

--10.Display the average inventory for each product ID.

Select Avg(Inventory) AS Avg_Inventory from Fact Group by ProductID


--11.Display state in a sequential order in a LocationTable.

Select state from Location Order by State ASC

/*-12.Display the average budget of the Product where the average budget
margin should be greater than 100.*/

Select Avg(Budget_Profit) AS Avg_Profit from Fact F Join Product P ON F.ProductId=P.ProductId Group by Product Having Avg( Budget_Margin) > 100


--13.What is the total sales done on date 2010-01-01?

Select SUM(Sales) AS TotalSales from Fact where Date='2010-01-01'

--14.Display the average total expense of each product ID on an individual date.

Select ProductId, Date, Avg(Total_Expenses) AS AvgExpenses from Fact Group by ProductId,Date 


/*15.Display the table with the following attributes such as date, productID,
product_type, product, sales, profit, state, area_code.*/

Select F.Date,P.ProductId,P.Product_Type,P.Product,F.Sales,F.Profit,L.State,L.Area_Code From Fact F Inner join Product P
ON P.ProductId=F.ProductId Inner Join Location L ON L.Area_Code = F.Area_Code

--16.Display the rank without any gap to show the sales wiserank.
 Select ProductID,Sales, Row_number() Over (Order by Sales desc) AS Saleswiserank from Fact;

--17.Find the state wise profit and sales.

Select State,SUM(F.Profit) AS Profit, SUM(F.Sales) AS Sales from Fact F Inner Join Location L ON  F.Area_code=L.Area_code Group by State


--18.Find the state wise profit and sales along with the productname.

Select P.Product,L.State,SUM(F.Profit) AS Profit, SUM(F.Sales) AS Sales from Fact F Inner Join Location L ON  F.Area_code=L.Area_code Inner Join 
Product P ON F.ProductId=P.ProductId Group by L.State,P.Product

--19.If there is an increase in sales of 5%, calculate the increasedsales.

Select Sales, Sales*1.05 AS IncreasedSales from Fact;

--20.Find the maximum profit along with the product ID and producttype.

Select P.Product, P.Product_type, Max(F.Profit) AS MaxProfit from Fact F Inner Join Product P ON F.ProductId=P.ProductId Group by P.Product,P.Product_type

/*21.Create a stored procedure to fetch the result according to theproduct type
from ProductTable.*/

Create Proc USP_Product
AS
(
Select Product_Type from Product
)

Exec USP_Product

/* 22.Write a query by creating a condition in which if the total expenses isless than
60 then it is a profit or else loss.*/


Select IIF(Total_Expenses < 60, 'Profit' ,'Loss') AS Output from Fact;


/*23.Give the total weekly sales value with the date and product IDdetails. Use
roll-up to pull the data in hierarchical order.*/

Select Date, ProductId, SUM(Sales) AS WeeklySales from Fact Group by ROLLUP (Date,ProductId)


/*24.Apply union and intersection operator on the tables which consistof
attribute area code.*/

Select Area_code from Fact
UNION 
Select Area_Code from Location

Select Area_code from Fact
Intersect
Select Area_Code from Location


/*25.Create a user-defined function for the product table to fetch a particular
product type based upon the user’s preference.*/

Create function UDF_Productfunc(@Product Varchar(50))
Returns Varchar(50)
AS
Begin
Return
(
Select @Product from Product where @Product=Product_Type
)

End


Select * from DBO.UDF_Productfunc('Coffee');



/*26.Change the product type from coffee to tea where product ID is 1and undo
it.*/

Begin Transaction
Update Product Set Product_Type='Tea' where ProductId=1

Rollback


/*27.Display the date, product ID and sales where total expensesare
between 100 to 200.*/

Select Date, ProductId,Sales from Fact where Total_Expenses between 100 and 200;

--28.Delete the records in the Product Table for regulartype.

Delete from Product where Type='Regular'

--29.Display the ASCII value of the fifth character from the column Product.

Select ASCII(Substring (CAST(Product AS Varchar(50)),5,1)) AS Output from Product

